"""Labelled synthetic waveform chunks for exercising the lane in tests.

Everything produced here carries `provenance.source == "synthetic"` with mandatory notes and
`float32le` encoding. It exists to prove plumbing (bus, stages, CAP rendering) with a signal
whose shape is known; it is never written under `data/` and never stands in for an
observation. The long-period burst is a windowed sinusoid, not a physical source model.
"""

from __future__ import annotations

from collections.abc import Iterator
from datetime import datetime, timedelta
from typing import Literal

import numpy as np

from serac.domain.seismic import (
    SeismicTrace,
    Sncl,
    TraceEncoding,
    TraceProvenance,
    TraceSource,
    sha256_of_bytes,
)

SyntheticKind = Literal["white_noise", "lp_burst"]

DEFAULT_SNCL = Sncl(network="XX", station="SYNTH", location="", channel="BHZ")


def _notes(kind: SyntheticKind, seed: int) -> str:
    return (
        f"synthetic {kind} generated by serac.streaming.synthetic (seed={seed}); "
        "not an observation; for plumbing tests only"
    )


def synthetic_samples(
    *,
    n: int,
    sampling_rate_hz: float,
    kind: SyntheticKind,
    seed: int,
    noise_std: float = 1.0,
    burst_start_s: float = 0.0,
    burst_duration_s: float = 0.0,
    burst_period_s: float = 20.0,
    burst_amplitude: float = 0.0,
) -> np.ndarray:
    """Gaussian noise, optionally with a Hann-windowed sinusoid added over a sub-interval."""
    rng = np.random.default_rng(seed)
    samples = rng.normal(0.0, noise_std, size=n).astype(np.float32)
    if kind == "lp_burst" and burst_duration_s > 0 and burst_amplitude != 0:
        t = np.arange(n, dtype=np.float64) / sampling_rate_hz
        inside = (t >= burst_start_s) & (t < burst_start_s + burst_duration_s)
        phase = (t[inside] - burst_start_s) / burst_duration_s
        window = 0.5 * (1.0 - np.cos(2.0 * np.pi * phase))
        burst = burst_amplitude * window * np.sin(2.0 * np.pi * t[inside] / burst_period_s)
        samples[inside] += burst.astype(np.float32)
    return samples


def synthetic_chunks(
    *,
    start_utc: datetime,
    n_chunks: int,
    chunk_seconds: float = 5.0,
    sampling_rate_hz: float = 20.0,
    sncl: Sncl = DEFAULT_SNCL,
    kind: SyntheticKind = "white_noise",
    seed: int = 0,
    noise_std: float = 1.0,
    burst_start_s: float = 0.0,
    burst_duration_s: float = 0.0,
    burst_period_s: float = 20.0,
    burst_amplitude: float = 0.0,
    notes: str | None = None,
) -> Iterator[SeismicTrace]:
    """Yield `n_chunks` consecutive float32 chunks of one synthetic channel.

    `burst_*` parameters position a long-period burst relative to `start_utc` (seconds) when
    `kind == "lp_burst"`. The same seed always yields the same bytes.
    """
    if start_utc.tzinfo is None:
        raise ValueError("start_utc must be timezone-aware")
    if n_chunks < 1 or chunk_seconds <= 0 or sampling_rate_hz <= 0:
        raise ValueError("n_chunks, chunk_seconds and sampling_rate_hz must be positive")
    per_chunk = round(chunk_seconds * sampling_rate_hz)
    if per_chunk < 1:
        raise ValueError("chunk_seconds * sampling_rate_hz must be at least one sample")
    total = per_chunk * n_chunks
    samples = synthetic_samples(
        n=total,
        sampling_rate_hz=sampling_rate_hz,
        kind=kind,
        seed=seed,
        noise_std=noise_std,
        burst_start_s=burst_start_s,
        burst_duration_s=burst_duration_s,
        burst_period_s=burst_period_s,
        burst_amplitude=burst_amplitude,
    )
    provenance = TraceProvenance(
        source=TraceSource.synthetic, server=None, notes=notes or _notes(kind, seed)
    )
    delta = 1.0 / sampling_rate_hz
    for index in range(n_chunks):
        block = samples[index * per_chunk : (index + 1) * per_chunk].astype("<f4")
        payload = block.tobytes()
        start = start_utc + timedelta(seconds=index * per_chunk * delta)
        end = start + timedelta(seconds=(per_chunk - 1) * delta)
        yield SeismicTrace(
            trace_id=f"{sncl.key}/{start.isoformat()}/{index}",
            sncl=sncl,
            start_time_utc=start,
            end_time_utc=end,
            sampling_rate_hz=sampling_rate_hz,
            npts=per_chunk,
            encoding=TraceEncoding.float32le,
            data=payload,
            data_sha256=sha256_of_bytes(payload),
            sequence=index,
            provenance=provenance,
        )


def synthetic_lp_burst(
    *,
    start_utc: datetime,
    n_chunks: int = 24,
    chunk_seconds: float = 5.0,
    sampling_rate_hz: float = 20.0,
    burst_start_s: float = 40.0,
    burst_duration_s: float = 40.0,
    burst_period_s: float = 20.0,
    burst_amplitude: float = 50.0,
    seed: int = 7,
) -> Iterator[SeismicTrace]:
    """Noise with a long-period (default 20 s period) burst: the `synthetic-lp-burst` run."""
    return synthetic_chunks(
        start_utc=start_utc,
        n_chunks=n_chunks,
        chunk_seconds=chunk_seconds,
        sampling_rate_hz=sampling_rate_hz,
        kind="lp_burst",
        seed=seed,
        burst_start_s=burst_start_s,
        burst_duration_s=burst_duration_s,
        burst_period_s=burst_period_s,
        burst_amplitude=burst_amplitude,
    )
